import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import CartProvider from "@/components/Providers";
import ShoppingCartModal from "@/components/ShoppingCartModal";
import Header from "@/components/Header";
import { ThemeProvider } from "@/components/theme/theme-provider";

const inter = Roboto({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="p-10">
      <body className={inter.className}>
        <ThemeProvider storageKey="igniteshop-theme" defaultTheme="dark">
          <CartProvider>
            <Header />
            <ShoppingCartModal />
            {children}
          </CartProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
